version: '3.8'

services:
  jnetwork:
    build: .
    container_name: jnetwork-app
    restart: always
    # MODE HOST: Agar bisa akses GenieACS (7557) di localhost STB secara langsung
    network_mode: host
    environment:
      - PORT=1987
      - POLL_INTERVAL=30
      # Karena pakai mode host, alamatnya cukup http://localhost:7557
      - GENIEACS_URL=http://localhost:7557
      - GENIEACS_USER=
      - GENIEACS_PASS=
    volumes:
      # Data Bapak akan tetap aman meskipun STB mati/restart
      - ./data:/app/backend/db/data
