version: '3.8'

services:
  jnetwork:
    build: .
    container_name: jnetwork-app
    restart: always
    ports:
      # Map STB's external port 1987 to internal port 1987
      - "1987:1987"
    environment:
      - PORT=1987
      - POLL_INTERVAL=30
      # OTOMATIS: Langsung sedot data dari port 7557 tanpa syarat
      - GENIEACS_URL=http://host.docker.internal:7557
      - GENIEACS_USER=
      - GENIEACS_PASS=
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Data Bapak akan tetap aman meskipun STB mati/restart
      - ./data:/app/backend/db/data
